from fastapi import APIRouter
from pydantic import BaseModel

router = APIRouter(
    prefix="/mail-assistant",
    tags=["Mail Assistant"]
)

_MOCK_DRAFTS_DB = [
    {
        "id": 1,
        "company_id": 1,
        "original_subject": "[견적문의] B2B 서비스 도입 견적 요청",
        "sender": "client@example.com",
        "category": "견적문의",
        "draft_reply": "안녕하세요. 카이로스 ERP 도입에 관심 가져주셔서 감사합니다. 첨부된 파일로 표준 견적서를 보내드립니다.",
        "status": "pending"
    }
]

class DraftApproval(BaseModel):
    action: str  # "approve", "reject", "edit"

@router.post("/scan")
def trigger_mail_scan(company_id: int = 1):
    """
    Endpoint to manually trigger scanning the Gmail Workspace for new emails.
    """
    # Logic to fetch emails using Gmail API, pass to Claude API for classification
    return {"message": "Mail scan initiated. Found 1 new email requiring reply.", "drafts_generated": 1}

@router.get("/drafts")
def get_ai_drafts(company_id: int = 1):
    """
    Retrieve email drafts automatically generated by AI.
    """
    company_drafts = [d for d in _MOCK_DRAFTS_DB if d["company_id"] == company_id]
    return {"drafts": company_drafts}

@router.post("/drafts/{draft_id}/action")
def take_action_on_draft(draft_id: int, approval: DraftApproval):
    """
    Approve, edit, or reject an AI-generated draft. If approved, sends via Gmail API.
    """
    for draft in _MOCK_DRAFTS_DB:
        if draft["id"] == draft_id:
            draft["status"] = "sent" if approval.action == "approve" else "rejected"
            return {"message": f"Draft {draft_id} {draft['status']} successfully."}

    return {"message": "Draft not found"}, 404
