from fastapi import APIRouter

router = APIRouter(
    prefix="/mail-assistant",
    tags=["Mail Assistant"]
)

@router.post("/scan")
def trigger_mail_scan():
    """
    Endpoint to manually trigger or act as a webhook for scanning the Gmail Workspace for new emails.
    """
    return {"message": "Mail scan initiated."}

@router.get("/drafts")
def get_ai_drafts():
    """
    Retrieve email drafts automatically generated by AI.
    """
    return {"drafts": []}

@router.post("/drafts/{draft_id}/approve")
def approve_and_send_draft(draft_id: int):
    """
    Approve an AI-generated draft and send it via Gmail API.
    """
    return {"message": f"Draft {draft_id} approved and sent."}
